# Project information
site_name: API Documentation - My Learning Path
# site_url:
site_author: Javier Hern치ndez Fern치ndez
site_description: >-
  My API documentation learning path through SDLC, OAS and Python.

# Repository
# repo_name: 
repo_url: 
#edit_uri: 
# Copyright
copyright: Copyright &copy; 2024 Javier Hern치ndez Fern치ndez

# Configuration
theme:
  icon:
    repo: fontawesome/brands/git-alt
  name: material
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - navigation.sections   
    - navigation.expand  
    - navigation.top 
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - search.suggest
  palette:
    - scheme: default
      primary: black
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode    
    - scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.ico
  icon:
    logo: assets/cube.png
  logo: assets/cube.png

  extra:
  status:
    new: Recently added
    deprecated: Outdated article


# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - tables
  - fenced_code
  - meta
  - wikilinks
  - md_in_html
  - sane_lists
  - toc:
      # permalink: true
      permalink: '#'
      baselevel: 1
      separator: '_'
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      auto_title: true
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

# Plugins  
# Page tree  

nav:  
  - Home: index.md    
  - Software Development Life Cycle:
      - Introduction: sdlc/index.md
      - Planning and Requirements Gathering: sdlc/planning-requirements/index.md  
      - System Design: sdlc/system-design/index.md  
      - Implementation: sdlc/implementation-coding/index.md  
      - Testing: sdlc/testing/index.md  
      - Deployment: sdlc/deployment/index.md  
      - Maintenance: sdlc/maintenance/index.md  
      - End-User Documentation: sdlc/end-user/index.md  
  - OpenAPI Specification: oas/index.md  
  - Code: code/index.md  
  - Changelog: changelog/index.md

